const assert = require('node:assert/strict');
require('../extension/navigation.js');
const N = globalThis.LectureNavigation;
const c = {canBind:true, course:'운영체제', title:'02_프로세스.mp4', pageKey:'https://example.test/courses/1', mediaKey:'https://example.test/stream'};
const rows = [{id:'1',course:'운영체제',title:'02 프로세스',created:1},{id:'2',course:'운영체제',title:'10 메모리',created:2},{id:'3',course:'철학',title:'02 프로세스',created:3}];
assert.equal(N.find(rows,c).id,'1');
assert.equal(N.find([...rows,{...rows[0],id:'duplicate'}],c),null);
assert.equal(N.find(rows,{...c,canBind:false}),null);
assert.equal(N.find(rows,{...c,course:''}),null);
assert.deepEqual(N.ordered(rows,'운영체제').map(l=>l.id),['1','2']);
const bound = {...rows[0],title:'사용자가 정한 노트명',bindings:[c]};
assert.equal(N.find([bound],c).id,'1');
assert.equal(N.find([bound],{...c,title:'다른 영상'}).id,'1');
assert.notEqual(N.identity(c),N.identity({...c,title:'다른 영상'}));
console.log('PASS: persistent video match, exact filename match, ambiguity protection, natural course order');
const youtube = {canBind:true, course:'youtube', title:'원래 제목', pageKey:'https://www.youtube.com/watch?v=abcdefghijk', mediaKey:''};
assert.equal(N.find([{id:'yt',bindings:[youtube]}], {...youtube,title:'변경된 제목'}).id, 'yt');
assert.equal(N.find([{id:'yt',bindings:[youtube]}], {...youtube,pageKey:'https://www.youtube.com/watch?v=12345678901'}), null);
const vm = require('node:vm'), fs = require('node:fs');
const media = {paused:false,ended:false,clientWidth:640,clientHeight:360,currentSrc:'https://stream.test/video?token=secret',getAttribute:()=>'',currentTime:0,duration:60};
const sandbox = {URL, URLSearchParams, location:new URL('https://www.youtube.com/watch?v=abcdefghijk&list=private'), document:{title:'Lesson - YouTube',querySelectorAll:q=>q==='video,audio'?[media]:[],querySelector:()=>null}};
vm.runInNewContext(fs.readFileSync(require.resolve('../extension/context.js'),'utf8'),sandbox);
assert.equal(sandbox.LectureContext.read().course,'youtube');
assert.equal(sandbox.LectureContext.read().pageKey,youtube.pageKey);
assert.equal(sandbox.LectureContext.read().mediaKey,'');
sandbox.location = new URL('https://www.youtube.com/shorts/12345678901');
assert.equal(sandbox.LectureContext.read().pageKey,'https://www.youtube.com/watch?v=12345678901');
// Paused/lazy YouTube pages can be explicitly linked before a video element exists.
sandbox.document.querySelectorAll=()=>[];
assert.equal(sandbox.LectureContext.read().canBind,true);
sandbox.location=new URL('https://www.youtube.com/');
assert.equal(sandbox.LectureContext.read().canBind,false);
sandbox.location=new URL('https://canvas.jejunu.ac.kr/courses/43319/modules/items/2864676');
sandbox.document.querySelectorAll=q=>q==='video,audio'?[]:[{href:'/courses/43319',textContent:'AI와인간관계의윤리학'},{href:'/courses/43319/modules',textContent:'모듈'}];
sandbox.document.querySelector=q=>q==='iframe'?{}:{textContent:'AI와 인간 관계의 윤리학_01_01'};
assert.equal(sandbox.LectureContext.read().course,'AI와인간관계의윤리학');
assert.equal(sandbox.LectureContext.read().canBind,true);
sandbox.location=new URL('https://canvas.jejunu.ac.kr/courses/43319');
assert.equal(sandbox.LectureContext.read().canBind,true);
